<?php
session_start();
if (!isset($_SESSION['admin'])) {
    header("Location: admin-login.php");
    exit;
}

// Include PostgreSQL database connection
require_once __DIR__ . '/../DB/DB_connection.php';

// Create reports folder if it doesn't exist
$reports_folder = 'reports';
if (!file_exists($reports_folder)) {
    mkdir($reports_folder, 0777, true);
}

// Get customer registration data (last 7 days)
$sql = "SELECT DATE(created_at) as date, COUNT(*) as count 
        FROM customers 
        WHERE created_at >= CURRENT_DATE - INTERVAL '7 days'
        GROUP BY DATE(created_at)
        ORDER BY date ASC";
$result = db_query($sql);

// Prepare CSV content
$csv_content = "Date,New Customers\n";

if ($result && db_num_rows($result) > 0) {
    while($row = db_fetch_assoc($result)) {
        $date = date('M d, Y', strtotime($row['date']));
        $count = $row['count'];
        $csv_content .= "$date,$count\n";
    }
} else {
    // If no data, add a note
    $csv_content .= "No data available,0\n";
}

// Add summary at the end
$csv_content .= "\n";
$csv_content .= "Report Generated," . date('Y-m-d H:i:s') . "\n";
$csv_content .= "Generated By,Admin\n";

// Create filename with timestamp
$filename = 'customer_registration_report_' . date('Y-m-d_His') . '.csv';
$filepath = $reports_folder . '/' . $filename;

// Save file to reports folder
file_put_contents($filepath, $csv_content);

// Also trigger download for user
header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . strlen($csv_content));
echo $csv_content;

exit;

?>
